### ISSUE TITLE
不开梯子时可以部署，但一旦开启梯子后就一直loading for NewBing，请问该如何设置？

### ISSUE THREAD

**Issue by kildren-coder** [xbzstudio/BingAI-Client#47]
Win10系统，梯子用Clash开启System Proxy后，程序就会不断重连，请问该如何调整？

报错日志（不断重复类似的内容）：

Traceback (most recent call last):
  File "I:\Python\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "I:\Python\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "I:\Python\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "I:\Python\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "I:\Python\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "I:\Python\lib\site-packages\starlette\middleware\cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "I:\Python\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "I:\Python\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "I:\Python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "I:\Python\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "I:\Python\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "I:\Python\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "I:\Python\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "I:\Python\lib\site-packages\fastapi\routing.py", line 289, in app
    await dependant.call(**values)
  File "../BingServer.py", line 320, in wsStream
    await ws.send_text(GenerateResponse().error(500, '未知错误', True))
  File "I:\Python\lib\site-packages\starlette\websockets.py", line 163, in send_text
    await self.send({"type": "websocket.send", "text": data})
  File "I:\Python\lib\site-packages\starlette\websockets.py", line 85, in send
    await self._send(message)
  File "I:\Python\lib\site-packages\starlette\middleware\exceptions.py", line 65, in sender
    await send(message)
  File "I:\Python\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 345, in asgi_send
    raise RuntimeError(msg % message_type)
RuntimeError: Unexpected ASGI message 'websocket.send', after sending 'websocket.close'.
[32mINFO[0m:     connection closed
[32mINFO[0m:     ('127.0.0.1', 8459) - "WebSocket /ws_stream" [accepted]
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "I:\Python\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "I:\Python\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "I:\Python\lib\site-packages\httpcore\backends\sync.py", line 58, in start_tls
    self._sock, server_hostname=server_hostname
  File "I:\Python\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "I:\Python\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "I:\Python\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "I:\Python\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "I:\Python\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "I:\Python\lib\site-packages\httpcore\_sync\connection_pool.py", line 261, in handle_request
    raise exc
  File "I:\Python\lib\site-packages\httpcore\_sync\connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "I:\Python\lib\site-packages\httpcore\_sync\http_proxy.py", line 272, in handle_request
    connect_request
  File "I:\Python\lib\site-packages\httpcore\_sync\connection.py", line 92, in handle_request
    raise exc
  File "I:\Python\lib\site-packages\httpcore\_sync\connection.py", line 69, in handle_request
    stream = self._connect(request)
  File "I:\Python\lib\site-packages\httpcore\_sync\connection.py", line 149, in _connect
    stream = stream.start_tls(**kwargs)
  File "I:\Python\lib\site-packages\httpcore\backends\sync.py", line 62, in start_tls
    raise exc
  File "I:\Python\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "I:\Python\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 0] Error

**Comment by xbzstudio** [comment]
为什么要开启梯子呢？开启梯子连接会十分慢的

**Comment by BenoitKAO** [comment]
首先,
感謝大大們開這個Github,
提供超棒的程式碼可以使用~

我當小白鼠幫大家測試過了,

現在是(2023/06/12)

為了避免大家同樣被制裁,
New bing現在已經會偵測BingAI-Clinet,
在BingAI-Clinet不能使用進階問答功能,
"基本"的問答還可以,
沒有提問的次數限制,
但是稍微複雜一點點的問題,
會立刻出現這個錯誤訊息.

如果想問複雜的問題,
建議大家乖乖回去Edge使用New Bing.

但是使用過BingAI-Clinet的帳號,
M$會給予懲罰,
現階段是在24小時內,
帳號會被打回New bing的原始使用者,
只能使用20次提問,
而且似乎也只能使用GPT 3.5,
我比較了我之前的問題,
回答內容有很大的不同.

現在是過了24小時帳號會解禁,
之後不知...

請大家注意和小心!

**Comment by lijiangdeshui2023** [comment]
是不是端口的原因，我的电脑不能用默认的80端口，所以就设置成90,。然后setting.js、server.json，都要改成90的端口。
