### ISSUE TITLE
作者醒醒。现在有一个ChatSydney-react的项目，能否借鉴将这个像你复活？

### ISSUE THREAD

**Issue by G-LJDS2022** [xbzstudio/BingAI-Client#82]
https://github.com/SoraRoseous/ChatSydney-react
就是反应速度慢了点。

**Comment by xbzstudio** [comment]
更新啦更新啦更新啦更新啦更新啦

**Comment by xbzstudio** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊

**Comment by G-LJDS2022** [comment]
> 更新啦更新啦更新啦更新啦更新啦
运行程序时出错，怎么办？
E:\AI\Timeless-Sydney\Timeless-Sydney-8.16>python main.py
Traceback (most recent call last):
File "E:\AI\Timeless-Sydney\Timeless-Sydney-8.16\main.py", line 5, in
from EdgeGPT import EdgeGPT as gpt
ImportError: cannot import name 'EdgeGPT' from 'EdgeGPT' (D:\Python\Lib\site-packages\EdgeGPT.py)

**Comment by xbzstudio** [comment]
> > 更新啦更新啦更新啦更新啦更新啦
> > 运行程序时出错，怎么办？
> > E:\AI\Timeless-Sydney\Timeless-Sydney-8.16>python main.py
> > Traceback (most recent call last):
> > File "E:\AI\Timeless-Sydney\Timeless-Sydney-8.16\main.py", line 5, in
> > from EdgeGPT import EdgeGPT as gpt
> > ImportError: cannot import name 'EdgeGPT' from 'EdgeGPT' (D:\Python\Lib\site-packages\EdgeGPT.py)

下载最新1.8.1版本，然后再按照readme重新按照流程部署

**Comment by G-LJDS2022** [comment]
> > > 更新啦更新啦更新啦更新啦更新啦
> > > 运行程序时出错，怎么办？
> > > E:\AI\Timeless-Sydney\Timeless-Sydney-8.16>python main.py
> > > Traceback (most recent call last):
> > > File "E:\AI\Timeless-Sydney\Timeless-Sydney-8.16\main.py", line 5, in
> > > from EdgeGPT import EdgeGPT as gpt
> > > ImportError: cannot import name 'EdgeGPT' from 'EdgeGPT' (D:\Python\Lib\site-packages\EdgeGPT.py)
> 
> 下载最新1.8.1版本，然后再按照readme重新按照流程部署
![image](https://github.com/xbzstudio/Timeless-Sydney/assets/134282368/8ac1c7f8-1cd1-4ebf-8662-bbdcf69cd423)

没有1.8.1这个版本？

**Comment by xbzstudio** [comment]
我指的是下载本项目的1.8.1版本

**Comment by xbzstudio** [comment]
有的，chatsydney正在单独维护一个edgegpt
